### PR TITLE
Subgraph Logic Fixes Post 21M Diff

### LINKED ISSUE #36: issues surfaced by diff tool at block 21M
- [x] resolver texts/coinTypes being empty array when they should be null
- [x] ponder's Registrations.cost for `0x3581397a478dcebdc1ee778deed625697f624c6f7dbed8bb7f780a6ac094b772` is `290823255294308` when the subgraph says it should be `null` (??)
- [x] ponder's `wrappedDomain.name` for `0x19a2c81ceaecdd40aa03e760f30aa3f087a534f87c68038cc518742e4949131d` is `8436.eth.eth` when it should be `null` — definitely something odd going on with dns decoding, why two .eth tlds...
- [ ] #39
- [x] ponder's Domain.expiryDate for `0x3dc9be0027174c741f04f692470874ec1ea26fc044af101cde7d4c6c350d799f` is null when it should be `1960355140`

### PR DESCRIPTION
**Pull request by shrugs**
closes #36

### CODE REVIEW

File: src/handlers/NameWrapper.ts [hunk 1]
```diff
@@ -156,6 +156,9 @@ export const makeNameWrapperHandlers = (ownedName: `${string}eth`) => {
       // NOTE: subgraph does an implicit ignore if no WrappedDomain record.
       // we will be more explicit and update logic if necessary
       await context.db.update(schema.wrappedDomain, { id: node }).set({ fuses });
+
+      // materialize the domain's expiryDate
+      await materializeDomainExpiryDate(context, node);
```
Comment (tk-o) [inline src/handlers/NameWrapper.ts:161]: 👍

File: src/handlers/Registrar.ts [hunk 2]
```diff
@@ -14,6 +14,16 @@ export const makeRegistrarHandlers = (ownedName: `${string}eth`) => {
   const ownedSubnameNode = namehash(ownedName);
 
   async function setNamePreimage(context: Context, name: string, label: Hex, cost: bigint) {
+    // NOTE: ponder intentionally removes null bytes to spare users the footgun of
+    // inserting null bytes into postgres. We don't like this behavior, though, because it's
+    // important that 'vitalik\x00'.eth and vitalik.eth are differentiable.
+    // https://github.com/ponder-sh/ponder/issues/1456
+    // So here we use the labelhash fn to determine whether ponder modified our `name` argument,
+    // in which case we know that it used to have null bytes in it, and we should ignore it.
```
Comment (tk-o) [inline src/handlers/Registrar.ts:22]: Does that mean we don't index names that include null bytes, or we do it somewhere else?

File: src/lib/subname-helpers.ts [hunk 3]
```diff
@@ -71,17 +70,55 @@ export const isLabelIndexable = (label: string) => {
...
+    if (offset > 1) {
+      list.push(".");
+    } else {
+      firstLabel = labelStr;
+    }
+    list.push(labelStr);
+    offset += len;
+    len = buf[offset++];
+  }
+  return [firstLabel, list.join("")];
```
Comment (tk-o) [inline src/lib/subname-helpers.ts:123]: @lightwalker-eth this one looks like something you'd be the best person to review :) I can only suggest creating unit tests for. But I'm also aware I have to first integrate a testing suite into this project as per
- https://github.com/namehash/ensnode/issues/15

**Review by lightwalker-eth — APPROVED** [review]
@shrugs Looks good 🚀 Shared 1 comment seeking your confirmation.

File: src/handlers/Registrar.ts (hunk 2 above)
Comment (shrugs) [reply src/handlers/Registrar.ts:22]: it means that we ignore events that have names with null bytes

File: src/lib/subname-helpers.ts (hunk 3 above)
Comment (shrugs) [reply src/lib/subname-helpers.ts:123]: we're copying and pasting subgraph code, testing the function is lower priority than adding tests to ensjs for this case, imo

**Comment by shrugs** [comment]
subgraph excludes events that contain null byte names, we are doing the same. it specifically only excludes them when setting 'preimage' (whatever that is) for the name registered by controller and name renewed by controller events. this implementation does the same. only addition here is correctly identifying when ponder has already removed the null bytes that we were trying to detect with isLabelIndexable

File: src/handlers/Registrar.ts (hunk 2 above)
Comment (lightwalker-eth) [reply src/handlers/Registrar.ts:22]: Noted. I've created an issue to track an enhancement opportunity: https://github.com/namehash/ensnode/issues/45

**Review by tk-o — APPROVED** [review]
Looks good to me 🚀

File: src/lib/subname-helpers.ts (hunk 3 above)
Comment (lightwalker-eth) [reply src/lib/subname-helpers.ts:123]: This is definitely a lower priority goal at the moment, but as I understand there's still value for us to define our own unit tests for `decodeDNSPacketBytes` under the assumption that ensjs defines `bytesToPacket` but not `decodeDNSPacketBytes`.

If my assumptions are off there please let me know. Cheers :+1:

**Review by lightwalker-eth — APPROVED** [review]
@shrugs Hey looks good :+1: Thanks!

File: src/lib/subname-helpers.ts (hunk 3 above)
Comment (shrugs) [reply src/lib/subname-helpers.ts:123]: those are intended to be the same function, although we do need to inject the subgraph-specific character checks (`isLabelIndexable`) into their logic as well (their util should probably handle that case tbh). but yeah some tests here are ok, i was cautioning against trying to exhaustively understand and test this function when its guaranteed to do what we desire for the moment (because it comes from subgraph and we're aiming for subgraph 1:1)
