### PR TITLE
fix: add _meta to subgraph compat endpoint

### LINKED ISSUE #178: bring the _meta field back
- need access to metadata store again

### PR DESCRIPTION
**Pull request by shrugs**
closes #178 
- uses data provider pattern via tko

### CODE REVIEW

**Comment by shrugs** [comment]
@tk-o does ponder meta/status export any value i could use for `hasIndexingErrors`? don't see anything obvious

File: packages/ponder-subgraph-api/src/graphql.ts [hunk 1]
```diff
@@ -584,6 +600,48 @@ export function buildGraphQLSchema(
...
+            }),
+          ),
+        },
+        deployment: { type: new GraphQLNonNull(GraphQLString) },
+        hasIndexingErrors: { type: new GraphQLNonNull(GraphQLBoolean) },
+      },
+    }),
+    resolve: async (_source, _args, context) => {
+      const status = await queryPonderStatus(metaConfig.schema, context.drizzle);
+      const mainnetStatus = status.find((status) => status.network_name === "1");
```
Comment (tk-o) [inline packages/ponder-subgraph-api/src/graphql.ts:627]: Does that mean we only need to support metadata for the mainnet ENS Deployment, and we don't need support for Sepolia or Holesky deployments?

**Review by tk-o — APPROVED** [review]
Looks awesome to me 🚀

File: apps/ensindexer/src/lib/ponder-metadata-provider.ts [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+    return meta.build_id;
+  };
+
+  /**
+   * Check if there are any indexing errors logged in the prometheus metrics
+   * @returns true if there are no indexing errors, false otherwise
+   */
+  const hasIndexingErrors = async () => {
+    const metrics = PrometheusMetrics.parse(await fetchPrometheusMetrics());
+    return metrics.getValue("ponder_indexing_has_error") === 1;
```
Comment (lightwalker-eth) [inline apps/ensindexer/src/lib/ponder-metadata-provider.ts:86]: Very interesting!

Suggest we create an issue to remind us to follow up on this with the Ponder team to verify our understanding of what this really signifies is correct.

My understanding is that the way this field works in GraphNode / the ENS Subgraph is it is used to identify that the indexing has stopped and is broken. When Ponder encounters an indexing error, as I understand it just terminates the `ponder start` process. GraphNode / the ENS Subgraph works differently. If there's an indexing error, the GraphNode process doesn't terminate itself. It just stops any effort to index the subgraph that has an indexing error and reflects that state in this field.

File: apps/ensindexer/src/lib/ponder-metadata-provider.ts [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+
+    return publicClient;
+  }
+
+  /**
+   * Get the last block indexed by Ponder.
+   *
+   * @returns the block info fetched from the public client
+   */
+  const getLastIndexedBlock = async () => {
```
Comment (lightwalker-eth) [inline apps/ensindexer/src/lib/ponder-metadata-provider.ts:53]: Suggest we strengthen the docs / function naming here to make it more clear how this function as currently written gets the last indexed block just for the root ENS deployment chain.

In other words, I understand we're working on goals right now that are for subgraph compat which is single chain only. In our context with Ponder suggest we take special care to describe how we're mapping from multichain contexts to a single chain context for subgraph compat.

**Review by lightwalker-eth — APPROVED** [review]
@shrugs Cool! Nice work 🚀 Shared a few small suggestions 🙌

File: apps/ensindexer/src/lib/ponder-metadata-provider.ts (hunk 2 above)
Comment (shrugs) [reply apps/ensindexer/src/lib/ponder-metadata-provider.ts:86]: this might be different in the case of the api service for `ponder serve` — not sure how this behaves #613
