### PR TITLE
Fix/ponder subgraph descriptions

### LINKED ISSUE #650: Rename ponder-subgraph package
# Goal

Rename the `ponder-subgraph-api` directory to just `ponder-subgraph` so that we maintain alignment between package names and the names of subdirectories under `/packages`

### LINKED ISSUE #673: Support GraphQL Schema Descriptions for Introspection / Inference
include the schema comments as GraphQL field descriptions or something
- llm inference
- human documentation in graphiql

### PR DESCRIPTION
**Pull request by shrugs**
- moves `ponder-subgraph-api` directory to `ponder-subgraph`, closes #650 
- adds descriptions derived from subgraph schema and ponder schema comments to subgraph api, closes #673
- it's not really reasonable to modify the ponder schema at the moment, it would require forking our own version of the graphql schema builder and maintaining that is not worth the effort at the moment.

### CODE REVIEW

**Comment by shrugs** [comment]
WAIT before reviewing this PR, i've seen an updated approach that i may attempt tomorrow https://www.npmjs.com/package/ponder-enrich-gql-docs-middleware

**Review by tk-o — APPROVED** [review]
Very clever approach, LGTM 🚀

**Comment by shrugs** [comment]
this PR is ready for review

**Review by 0xBison — APPROVED** [review]

File: packages/ponder-subgraph/src/graphql.ts [hunk 1]
```diff
@@ -613,8 +614,14 @@ export function buildGraphQLSchema({
...
         },
-        deployment: { type: new GraphQLNonNull(GraphQLString) },
-        hasIndexingErrors: { type: new GraphQLNonNull(GraphQLBoolean) },
+        deployment: {
+          type: new GraphQLNonNull(GraphQLString),
+          description: "A unique ID representing this instance of ENSNode.",
+        },
+        hasIndexingErrors: {
+          type: new GraphQLNonNull(GraphQLBoolean),
+          description: "If true, ENSNode encountered indexing errors at some past block.",
```
Comment (lightwalker-eth) [inline packages/ponder-subgraph/src/graphql.ts:623]: @shrugs I haven't reviewed the details of how we generate this value. My assumption is that the ENSIndexer instance running `ponder serve` is somehow checking if the related ENSIndexer service running `ponder start` has crashed or not?

My understanding is that whenever ENSIndexer encounters an indexing error it just crashes itself.

Appreciate your advice. Suggest we invest efforts into our docs to help people understand how this case is handled. It's a good situation to document!

**Review by lightwalker-eth — APPROVED** [review]
@shrugs Awesome work here! 🚀

**Comment by lightwalker-eth** [comment]
@shrugs Could you please also do another check for other places in our docs or configs that might need to be renamed? Thanks :+1:

CleanShot 2025-05-07 at 18 17 11

CleanShot 2025-05-07 at 18 19 28
