### PR TITLE
fix(ensadmin): improve ENSNode response validation errors

### LINKED ISSUE #468: ENSAdmin: Bug When API is down
mainnet blue is currently down and there's a client side parsing error in ensadmin because of it. looks like it's caught by the error boundary. can't get a stacktrace because we minify — maybe worth enabling source maps in production for the near future, since we don't have a bug reporting tooling set up?

https://admin.ensnode.io/status?ensnode=https%3A%2F%2Fapi.mainnet.blue.ensnode.io%2F

Image

### PR DESCRIPTION
**Pull request by tk-o**
This PR updates ENSNode metadata response validation to also check if the last indexed block data was provided.
> Note: The validation will turn into robust parsing with another PR: #475 

### Preview

image

### Changes included
- updated ENSNode data validation logic
- updated ENSNode data fetching error message to be more user-friendly
- addresses security audit issues
  - https://github.com/namehash/ensnode/security/dependabot/17
  - https://github.com/namehash/ensnode/security/dependabot/18
  - https://github.com/namehash/ensnode/security/dependabot/19
- ensure a proper React Query client initialisation
  - use a single QueryClientProvider in the app
  - make new client instance for each server-side request
  - make a single instance and re-use it for client-side requests
- fixed React dev errors about SVG markup syntax
- enable source maps in production for easier debugging in the future
  - ENSAdmin app is open source and uses no secrets for its runtime

Resolves #468

### CODE REVIEW

File: apps/ensadmin/src/app/ponder-client-api/provider.tsx [hunk 1]
```diff
@@ -16,7 +15,7 @@ export function Provider({ url, children }: ProviderProps) {
 
   return (
     <PonderProvider client={ponderClient}>
-      <QueryClientProvider>{children}</QueryClientProvider>
+      {children}
```
Comment (tk-o) [inline apps/ensadmin/src/app/ponder-client-api/provider.tsx:18]: There's a global QueryClientProvider set with the global WagmiProvider. No need for more ;)

**Comment by djstrong** [comment]
I am not sure if this should fix this issue but when I choose an endpoint which results in error then I can't change it to other endpoint.

**Review by lightwalker-eth — COMMENTED** [review]
@tk-o Hey cool! Looks nice to me! Will defer to others on the team for final review 🙌

**Review by lightwalker-eth — APPROVED** [review]
@tk-o Overall happy to approve this PR, but there's a few items to fix first:

1. Please see issue reported in Slack: https://namehash.slack.com/archives/C086Z6FNBHN/p1743677290321439?thread_ts=1743654609.022999&cid=C086Z6FNBHN
   1. Please either fix this in this PR, or create a new GitHub issue that describes the issue that we can follow up with soon.
1. Please fix merge conflicts.

**Comment by tk-o** [comment]
@lightwalker-eth I logged the issue:
- https://github.com/namehash/ensnode/issues/511

I believe it's not linked to this PR changes, so will fix it in a separate one.
