### PR TITLE
Integrate ENSDb health check and readiness check into ENSApi probe endpoints

### LINKED ISSUE #1227: Add postgres liveness to ensapi healthcheck
it's not technically a sync dependency for liveness but it seems reasonable that if postgres is broken we want the whole environment to be considered unhealthy

### PR DESCRIPTION
**Pull request by tk-o**
# Lite PR

[Tip: Review docs on the ENSNode PR process](https://ensnode.io/docs/contributing/prs)

## Summary

- The following ENSApi probe endpoints were updated:
  - The `/health` endpoint returns the response based on the ENSDb instance health check.
  - The `/ready` endpoint returns the response based on the ENSDb instance readiness check.
- OpenAPI spec now includes both ENSApi probe endpoints
- ENSDb SDK
  - The readiness check has been simplified to just running a target query against ENSDb instance. If that query is successful.

---

## Why

- Changes were requested in issue #1227 

---

## Testing

- I ran ENSIndexer instance and ENSApi instance locally
- I observed that the Indexing Metadata Context record appeared in ENSDb.
- I tested ENSApi endpoints, both `/health` and `/ready` returned `200 OK`
- I deleted the Indexing Metadata Context record from ENSDb.
- I tested ENSApi endpoints again, `/health` returned `200 OK`, and `/ready` returned `503 Service Unavailable`.

---

## Notes for Reviewer (Optional)

- Anything non-obvious or worth a heads-up.

---

## Pre-Review Checklist (Blocking)

- [x] This PR does not introduce significant changes and is low-risk to review quickly.
- [x] Relevant changesets are included (or are not required)

Resolves #1227

### CODE REVIEW

**Comment by tk-o** [comment]
@greptile review

File: apps/ensapi/src/app.ts [hunk 1]
```diff
@@ -65,7 +66,35 @@ app.get("/openapi.json", (c) => {
 });
 
 app.get("/health", async (c) => {
-  return c.json({ message: "fallback ok" });
+  try {
+    const isEnsDbHealthy = await ensDbClient.isHealthy();
+
+    if (!isEnsDbHealthy) {
+      throw new Error(`ENSDb instance is unhealthy`);
```
Comment (sevenzing) [inline apps/ensapi/src/app.ts]: hm, does it make sense to also send `json` with 503? I can imagine that `throw Error` might be resolved as json but this is too implicit. also we have line 79 where we send error explicitly

Comment (tk-o) [reply apps/ensapi/src/app.ts]: Yeah, we send the JSON response with 503 response code in the line 79 (the catch block).

File: .changeset/ready-hands-worry.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"ensapi": minor
+---
+
+Integrated ENSDb health check and readiness check into relevant ENSApi probe endpoints.
```
Comment (lightwalker-eth) [inline .changeset/ready-hands-worry.md]: Should the description of this PR be updated to identify how it will close issue 1227? I note that it doesn't do that currently.

File: apps/ensapi/src/app.ts [hunk 3]
```diff
@@ -65,7 +66,35 @@ app.get("/openapi.json", (c) => {
 });
 
 app.get("/health", async (c) => {
```
Comment (lightwalker-eth) [inline apps/ensapi/src/app.ts]: What updates should be made here to make it so we have all the nice info about this REST API endpoint in the OpenAPI spec, including the different possible error codes, example responses, etc?

File: apps/ensapi/src/app.ts [hunk 4]
```diff
@@ -65,7 +66,35 @@ app.get("/openapi.json", (c) => {
...
+    }
+
+    return c.json({ responseCode: "ok" });
+  } catch (error) {
+    logger.debug(error, "Health check failed");
+    return c.json({ responseCode: "error", message: "Service Unavailable" }, 503);
+  }
+});
+
+app.get("/ready", async (c) => {
```
Comment (lightwalker-eth) [inline apps/ensapi/src/app.ts]: What updates should be made here to make it so we have all the nice info about this REST API endpoint in the OpenAPI spec, including the different possible error codes, example responses, etc?

File: .changeset/ready-hands-worry.md (hunk 2 above)
Comment (lightwalker-eth) [inline .changeset/ready-hands-worry.md]:
```suggestion
Integrated ENSDb health check and readiness check into ENSApi `/health` and `/ready` endpoints.
```

**Review by lightwalker-eth — APPROVED** [review]
@tk-o Looks good 👍 Shared a few suggestions. Please feel welcome to take the lead to merge when ready!
