### PR TITLE
WIP: fixes for ensjs surfaced by ens-test-env & ensjs test suite

### LINKED ISSUE #78: Subgraph-Compat: Filters & Null Filters
- [x] support entity bare relation filters as shorthand for primary key filter

```gql
# subgraph
query Resolver {
  resolvers(where:{addr: "0xf99b11016b4e9ab00226446af3715610359fa8cd"}, first: 1) {
    id
  }
}
```

- [x] support `null` as a value for a Filter (inc. `_not: null`)

```gql
# subgraph
query Resolver {
  resolvers(where:{addr_not: "0xf99b11016b4e9ab00226446af3715610359fa8cd"}, first: 1) {
    id
  }
}
```

### LINKED ISSUE #129: verify ensjs tests passing with ensnode subgraph-compat api
- [x] support lowercase AND and OR operators

```
Variable "$whereFilter" got invalid value { and: [{ or: [Array] }, { parent_not: "0x91d1777781884d03a6757a803996e38de2a42967fb37eeaca72729271025a9e2" }, { or: [Array] }, { or: [Array] }] }; Field "and" is not defined by type "Domain_filter". Did you mean "AND" or "id"?: {"response":{"errors":[{"message":"Variable \"$whereFilter\" got invalid value { and: [{ or: [Array] }, { parent_not: \"0x91d1777781884d03a6757a803996e38de2a42967fb37eeaca72729271025a9e2\" }, { or: [Array] }, { or: [Array] }] }; Field \"and\" is not defined by type \"Domain_filter\". Did you mean \"AND\" or \"id\"?","locations":[{"line":1,"column":98}]}],"status":200,"headers":{}},"request":{"query":"\n    query getNamesForAddress(\n      $orderBy: Domain_orderBy\n      $orderDirection: OrderDirection\n      $first: Int\n      $whereFilter: Domain_filter\n    ) {\n      domains(\n        orderBy: $orderBy\n        orderDirection: $orderDirection\n        first: $first\n        where: $whereFilter\n      ) {\n        ...DomainDetails\n        registration {\n          ...RegistrationDetails\n        }\n        wrappedDomain {\n          ...WrappedDomainDetails\n        }\n      }\n    }\n    \n  fragment DomainDetails on Domain {\n    ...DomainDetailsWithoutParent\n    parent {\n      name\n    }\n  }\n  \n  fragment DomainDetailsWithoutParent on Domain {\n    id\n    labelName\n    labelhash\n    name\n    isMigrated\n    createdAt\n    resolvedAddress {\n      id\n    }\n    owner {\n      id\n    }\n    registrant {\n      id\n    }\n    wrappedOwner {\n      id\n    }\n  }\n\n\n    \n  fragment RegistrationDetails on Registration {\n    registrationDate\n    expiryDate\n  }\n\n    \n  fragment WrappedDomainDetails on WrappedDomain {\n    expiryDate\n    fuses\n  }\n\n  ","variables":{"orderBy":"name","orderDirection":"asc","first":100,"whereFilter":{"and":[{"or":[{"owner":"0x70997970c51812dc3a010c7d01b50e0d17dc79c8"},{"registrant":"0x70997970c51812dc3a010c7d01b50e0d17dc79c8"},{"resolvedAddress":"0x70997970c51812dc3a010c7d01b50e0d17dc79c8"},{"wrappedOwner":"0x70997970c51812dc3a010c7d01b50e0d17dc79c8"}]},{"parent_not":"0x91d1777781884d03a6757a803996e38de2a42967fb37eeaca72729271025a9e2"},{"or":[{"expiryDate_gt":"1739403868"},{"expiryDate":null}]},{"or":[{"owner_not":"0x0000000000000000000000000000000000000000"},{"resolver_not":null},{"and":[{"registrant_not":"0x0000000000000000000000000000000000000000"},{"registrant_not":null}]}]}]}}}}
```

- [x] `Domain.registration` relationship is null when relationship does exists
  - error is in graphql.ts somewhere, since this works in ponder's api
- [x] relational filters (like `{ owner: String }` and `{ owner_not: String }`
- [x] natural sort order for string fields
- [x] nullable fields

### LINKED ISSUE #272: update to ponder 0.9.17, re-enable anvil `disableCache`
https://github.com/ponder-sh/ponder/issues/1513

### PR DESCRIPTION
**Pull request by shrugs**
closes #129 
closes #272 
closes #78

### CODE REVIEW

File: packages/ponder-schema/src/collate.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+// https://github.com/drizzle-team/drizzle-orm/issues/638
+export function monkeypatchCollate(col: any, collation: string) {
```
Comment (lightwalker-eth) [inline packages/ponder-schema/src/collate.ts:2]: Nice

File: packages/ponder-subgraph-api/src/graphql.ts [hunk 2]
```diff
@@ -1,11 +1,16 @@
 /**
- * This is an autogenerated graphql schema, initially based on ponder's, designed to mimic
- * the subgraph graphql api for queries we've deemed relevant (see docs).
+ * This is graphql schema generated from a drizzle schema, initially based on ponder's.
```
Comment (lightwalker-eth) [inline packages/ponder-subgraph-api/src/graphql.ts:2]:
```suggestion
 * This is a graphql schema generated from a drizzle (sql) schema, initially based on ponder's.
```

Also suggest clarifying more specifically initially based on ponder’s refers to. Ponder’s GraphQL schema? Or their strategy? Or their implementation? Etc?

File: packages/ponder-subgraph-api/src/graphql.ts [hunk 3]
```diff
@@ -1,11 +1,16 @@
...
+ * Its goal is to mimic the subgraph graphql api for queries we've deemed relevant (see docs).
  *
  * 1. inlines some ponder internal types
- * 2. removes ponder's encoded id params in favor of literal ids
- * 3. implement subgraph's simpler pagination style with first & skip w/out Page types
- * 4. PascalCase entity names
+ * 2. implement subgraph's simpler pagination style with first & skip w/out Page types
```
Comment (lightwalker-eth) [inline packages/ponder-subgraph-api/src/graphql.ts:6]: This is all so cool 🚀

File: packages/ponder-subgraph-api/src/graphql.ts [hunk 4]
```diff
@@ -850,16 +895,49 @@ export function buildDataLoaderCache({ drizzle }: { drizzle: Drizzle<Schema> })
...
+          );
 
           const rows = await baseQuery.findMany({
             where: or(...idConditions),
-            limit: ids.length,
+            limit: encodedIds.length,
           });
 
-          return ids.map((id) => rows.find((row) => row.id === id));
+          // Now, we need to order the rows coming out of the database to match
```
Comment (lightwalker-eth) [inline packages/ponder-subgraph-api/src/graphql.ts:912]: Nice !

**Review by lightwalker-eth — APPROVED** [review]
@shrugs Big milestone! Looks great 🚀
