### PR TITLE
fix(unique-id): use unique ids for cross-registrar entities

### LINKED ISSUE #107: Error while processing '/eth/linea/Registry:NewOwner'
```
6:57:22 AM WARN  user       Failed 'new_owners.insert()' database method 
6:57:22 AM ERROR indexing   Error while processing '/eth/linea/Registry:NewOwner' event in 'linea' block 6685403
UniqueConstraintError: Unique constraint failed for 'new_owners'.
    at /app/apps/ensnode/src/handlers/Registry.ts:168:5
  166 |
  167 |     // log DomainEvent
> 168 |     await context.db.insert(schema.newOwner).values({
      |     ^
  169 |       ...sharedEventValues(event),
  170 |
  171 |       parentDomainId: node,
db.insert arguments:
  id               6685403-1
  blockNumber      6685403
  transactionID    0xcc7347441525e53f4d4c1ad19807ecf030c0e236e7a910b94b178062c3e4157a
  parentDomainId   0x527aac89ac1d1de5dd84cff89ec92c69b028ce9ce3fa3d654882474ab4402ec3
  domainId         0x7765b9d5c2a589fa10aeffae57e16dbf783db2a80d11eb6c76e1260625fa89b4
  ownerId          0xA53cca02F98D590819141Aa85C891e2Af713C223
Event arguments:
  node    0x527aac89ac1d1de5dd84cff89ec92c69b028ce9ce3fa3d654882474ab4402ec3
  label   0x2244051571514b3ea74fb776d03d6d70a9fbaba3a2b33e63f8a805321f4e0a08
  owner   0xA53cca02F98D590819141Aa85C891e2Af713C223
Log:
  index     1
  address   0x50130b669B28C339991d8676FA73CF122a121267
Transaction:
  hash   0xcc7347441525e53f4d4c1ad19807ecf030c0e236e7a910b94b178062c3e4157a
  from   0x3357e73873944D885c5496718D0A1326f2Cab9B4
  to     0xDb75Db974B1F2bD3b5916d503036208064D18295
Block:
  hash        0x6bb74bcea217dbeabd3b5d75f91cecca29740349b57d0306872efe7927c0f304
  number      6685403
  timestamp   1720774022
6:57:22 AM INFO  app        Indexed 25339 events with 93.0% complete and 6s remaining
6:57:22 AM WARN  process    Encountered indexing error, starting shutdown sequence
6:57:23 AM FATAL process    Finished shutdown sequence, terminating (exit code 1)
/app/apps/ensnode:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ensnode@0.0.1 start: `ponder start`
Exit status 1
```

### PR DESCRIPTION
**Pull request by tk-o**
This PR changes the way ID values get created for DB entities. The Subgraph-compatible entities assumed the single chain being source of data. However, the ENSNode uses multi-chain data which sometimes causes ID conflicts. With this change, the all plugins, except for the `eth` one, will use prefixed IDs.

Resolves #107

### CODE REVIEW

File: apps/ensnode/src/lib/ids.ts [hunk 1]
```diff
@@ -5,12 +5,26 @@ import type { Address, Hex } from "viem";
 export const makeResolverId = (address: Address, node: Hex) =>
   [address.toLowerCase(), node].join("-");
 
-// https://github.com/ensdomains/ens-subgraph/blob/master/src/utils.ts#L5
-// produces `blocknumber-logIndex` or `blocknumber-logindex-transferindex`
-export const makeEventId = (blockNumber: bigint, logIndex: number, transferIndex?: number) =>
-  [blockNumber.toString(), logIndex.toString(), transferIndex?.toString()]
-    .filter(Boolean)
-    .join("-");
+export const makeEventId = (
```
Comment (lightwalker-eth) [inline apps/ensnode/src/lib/ids.ts:8]: @tk-o I imagine the updated code here all works great. However one of our goals is to make it easy for other devs to review our code and ensure its in alignment with the ENS Subgraph's code.

Is there another way you could achieve our goals here that optimizes for making it super easy to read and verify equivalence with the ENS Subgraph's code?

Let's optimize this not for the CPU or fanciness, but for other humans who will come after us to review this code. Let's make our code really boring and easy to be confident that it's in alignment with the ENS Subgraph's logic.

**Review by lightwalker-eth — CHANGES_REQUESTED** [review]
@tk-o Hey thanks for this fix! Your overall strategy looks good to me.

Left a few small comments. There's one key change request though before I'm comfortable approving. Thanks!

File: apps/ensnode/src/handlers/NameWrapper.ts [hunk 2]
```diff
@@ -40,50 +40,51 @@ async function materializeDomainExpiryDate(context: Context, node: Node) {
...
-async function handleTransfer(
-  context: Context,
-  event: EventWithArgs,
-  eventId: string,
-  tokenId: bigint,
-  to: Address,
-) {
-  await upsertAccount(context, to);
-  const node = tokenIdToNode(tokenId);
+export const makeNameWrapperHandlers = (ownedName: OwnedName) => {
```
Comment (tk-o) [inline apps/ensnode/src/handlers/NameWrapper.ts:43]: I had to wrap multiple exports into a factory function that would allow passing extra context to those previously-exported functions. Haven't changed logic of any of these functions.

File: apps/ensnode/src/handlers/Registry.ts [hunk 3]
```diff
@@ -76,172 +77,179 @@ async function recursivelyRemoveEmptyDomainFromParentSubdomainCount(context: Con
...
-    // note that we set isMigrated so that if this domain is being interacted with on the new registry, its migration status is set here
-    let domain = await context.db.find(schema.domain, { id: subnode });
-    if (domain) {
-      // if the domain already exists, this is just an update of the owner record (& isMigrated)
-      await context.db.update(schema.domain, { id: domain.id }).set({ ownerId: owner, isMigrated });
-    } else {
-      // otherwise create the domain
-      domain = await context.db.insert(schema.domain).values({
-        id: subnode,
+export const makeRegistryHandlers = (ownedName: OwnedName) => {
```
Comment (tk-o) [inline apps/ensnode/src/handlers/Registry.ts:80]: I had to wrap multiple exports into a factory function that would allow passing extra context to those previously-exported functions. Haven't changed logic of any of these functions.

File: apps/ensnode/src/handlers/Resolver.ts [hunk 4]
```diff
@@ -2,341 +2,349 @@ import { type Context } from "ponder:registry";
...
-export async function handleDNSZonehashChanged({
-  context,
-  event,
-}: {
-  context: Context;
-  event: EventWithArgs<{ node: Hex; zonehash: Hex }>;
-}) {
-  // subgraph ignores
-}
+export const makeResolverHandlers = (ownedName: OwnedName) => {
```
Comment (tk-o) [inline apps/ensnode/src/handlers/Resolver.ts:17]: I had to wrap multiple exports into a factory function that would allow passing extra context to those previously-exported functions. Haven't changed logic of any of these functions.

File: apps/ensnode/src/lib/ids.ts (hunk 1 above)
Comment (tk-o) [reply apps/ensnode/src/lib/ids.ts:8]: Sure, we can provide inline `if/else` blocks to make the code easier to read. Will use less meta programming in the future to allow logic remain obvious.

**Comment by tk-o** [comment]
I will re-create this PR with ease of review in mind.

File: apps/ensnode/src/lib/ids.ts (hunk 1 above)
Comment (shrugs) [reply apps/ensnode/src/lib/ids.ts:8]: i really like the cleanliness of this file after your changes, but i think the function can be simply written as:

```ts
export const makeEventId = (ownedName: OwnedName, blockNumber: bigint, logIndex: number, transferIndex?: number) =>
  [ownedName === 'eth' ? undefined : ownedName, blockNumber.toString(), logIndex.toString(), transferIndex?.toString()]
    .filter(Boolean)
    .join("-");
```

and we can remove the `makeId` helper. `makeRegistrationId` can similarly be left as-is, in my opinion.

---

in the future, when writing a function like `makeId`, using named arguments could make the api surface easier to read, like `selectByOwnedName(ownedName, { eth: labelhash, else: node })` or something like that. sort of inspired by functional programming. just a suggestion.

**Review by shrugs — COMMENTED** [review]
LGTM, minus `ids.ts` suggestion

File: apps/ensnode/src/lib/ids.ts (hunk 1 above)
Comment (tk-o) [reply apps/ensnode/src/lib/ids.ts:22]: Totally right, I've fixed it accordingly.

File: apps/ensnode/src/lib/ids.ts [hunk 5]
```diff
@@ -37,18 +59,5 @@ export const makeEventId = (blockNumber: bigint, logIndex: number, transferIndex
  * @returns a unique registration id
  */
 export const makeRegistrationId = (registrarName: string, labelHash: Labelhash, node: Node) => {
-  if (registrarName === "eth") {
```
Comment (lightwalker-eth) [inline apps/ensnode/src/lib/ids.ts:40]: Please bring back the old version of `makeRegistrationId`. Its important to not remove the carefully crafted comments that were here before.

File: apps/ensnode/src/lib/ids.ts [hunk 6]
```diff
@@ -5,10 +5,32 @@ import type { Address, Hex } from "viem";
 export const makeResolverId = (address: Address, node: Hex) =>
   [address.toLowerCase(), node].join("-");
 
-// https://github.com/ensdomains/ens-subgraph/blob/master/src/utils.ts#L5
```
Comment (lightwalker-eth) [inline apps/ensnode/src/lib/ids.ts:8]: Let's please retain links to related Subgraph code.

File: apps/ensnode/src/lib/ids.ts [hunk 7]
```diff
@@ -5,10 +5,32 @@ import type { Address, Hex } from "viem";
...
-// produces `blocknumber-logIndex` or `blocknumber-logindex-transferindex`
-export const makeEventId = (blockNumber: bigint, logIndex: number, transferIndex?: number) =>
-  [blockNumber.toString(), logIndex.toString(), transferIndex?.toString()]
+/**
+ * Makes a cross-registrar unique event ID.
+ *
+ * The ENS Subgraph indexes events from a single chain. However, ENSNode indexes
```
Comment (lightwalker-eth) [inline apps/ensnode/src/lib/ids.ts:11]:
```suggestion
 * The ENS Subgraph indexes events from a single registrar. However, ENSNode enables indexing of
```

File: apps/ensnode/src/lib/ids.ts [hunk 8]
```diff
@@ -5,10 +5,32 @@ import type { Address, Hex } from "viem";
...
+ * events from multiple chains, which can lead to event ID collisions. This
```
Comment (lightwalker-eth) [inline apps/ensnode/src/lib/ids.ts:12]:
```suggestion
 * events from multiple registrars, which can lead to event ID collisions. This
```

File: apps/ensnode/src/lib/ids.ts [hunk 9]
```diff
@@ -5,10 +5,32 @@ import type { Address, Hex } from "viem";
...
+ * function allows keeping Subgraph-compatible event IDs while ensuring
+ * uniqueness across chains.
+ *
+ * @param registrarName the name of the registrar issuing the registration
```
Comment (lightwalker-eth) [inline apps/ensnode/src/lib/ids.ts:16]:
```suggestion
 * @param registrarName the name of the registrar associated with the event
```

**Review by lightwalker-eth — CHANGES_REQUESTED** [review]
@tk-o Thanks for updates. I especially appreciate the comments you added to your own PR to communicate how files with a bunch of track changes should be interpreted during PR review.

File: apps/ensnode/src/lib/ids.ts (hunk 5 above)
Comment (shrugs) [reply apps/ensnode/src/lib/ids.ts:40]: just to confirm, you mean just the comments, yeah? function impl is clearer in this version

Comment (lightwalker-eth) [reply apps/ensnode/src/lib/ids.ts:40]: Prefer everything about the old version of this function.

Comment (shrugs) [reply apps/ensnode/src/lib/ids.ts:40]: gotcha, in that case @tk-o let's continue to use the makeId funtion (or whatever you end up calling it) for the event id as well, apologies for the misdirection

Comment (lightwalker-eth) [reply apps/ensnode/src/lib/ids.ts:40]: I think there's a misunderstanding. Not suggesting to bring the makeId function back. It's good that's removed.

Please check the full diff this PR is proposing to make against main.

Comment (tk-o) [reply apps/ensnode/src/lib/ids.ts]: @lightwalker-eth yes, I get what you mean. I guess I had too much back and forth with the implementations I was proposing only to realise that the original had been just fine ;)

**Review by lightwalker-eth — APPROVED** [review]
@tk-o Nice! Thanks for the fixes. Approved 🚀
